import pic from './pic.jpg';

const productApiData = [
    {
        id: 1,
        title: 'Basic Tee',
        href: '#',
        thumbnail: pic,
        imageAlt: "Front of men's Basic Tee in black.",
        price: '350',
        category: 'Black',
    },
    {
        id: 2,
        title: 'Sport Shoes',
        href: '#',
        thumbnail: pic,
        imageAlt: "Side view of Sport Shoes.",
        price: '1200',
        category: 'Footwear',
    },
    {
        id: 3,
        title: 'Casual Hoodie',
        href: '#',
        thumbnail: pic,
        imageAlt: "Front of Casual Hoodie in grey.",
        price: '850',
        category: 'Hoodies',
    },
    {
        id: 4,
        title: 'Leather Wallet',
        href: '#',
        thumbnail: pic,
        imageAlt: "Close-up of Leather Wallet.",
        price: '600',
        category: 'Accessories',
    },
    {
        id: 5,
        title: 'Summer Hat',
        href: '#',
        thumbnail: pic,
        imageAlt: "Side view of Summer Hat.",
        price: '250',
        category: 'Hats',
    },
    {
        id: 6,
        title: 'Basic Jeans',
        href: '#',
        thumbnail: pic,
        imageAlt: "Front of men's Basic Jeans.",
        price: '950',
        category: 'Denim',
    },
    {
        id: 7,
        title: 'Elegant Watch',
        href: '#',
        thumbnail: pic,
        imageAlt: "Close-up of Elegant Watch.",
        price: '2000',
        category: 'Accessories',
    },
    {
        id: 8,
        title: 'Running Shorts',
        href: '#',
        thumbnail: pic,
        imageAlt: "Front of Running Shorts in blue.",
        price: '400',
        category: 'Activewear',
    },
    {
        id: 9,
        title: 'Comfy Slippers',
        href: '#',
        thumbnail: pic,
        imageAlt: "Top view of Comfy Slippers.",
        price: '300',
        category: 'Footwear',
    },
    {
        id: 10,
        title: 'Classic Cap',
        href: '#',
        thumbnail: pic,
        imageAlt: "Top view of Classic Cap in red.",
        price: '150',
        category: 'Hats',
    },
];

export default productApiData;